import '../../data_models/workout.dart';

final List<Workout> dummyWorkouts = [
  Workout(
    id: 1,
    title: "Full Body Workout",
    description: "Complete full body workout routine",
    durationMinutes: 45,
    difficulty: "Intermediate",
  ),
  Workout(
    id: 2,
    title: "Morning Yoga",
    description: "Gentle yoga for flexibility",
    durationMinutes: 30,
    difficulty: "Beginner",
  ),
  Workout(
    id: 3,
    title: "HIIT Cardio",
    description: "High intensity cardio workout",
    durationMinutes: 20,
    difficulty: "Advanced",
  ),
  Workout(
    id: 4,
    title: "Upper Body Strength",
    description: "Build strength in chest, shoulders, and arms",
    durationMinutes: 40,
    difficulty: "Intermediate",
  ),
  Workout(
    id: 5,
    title: "Lower Body Blast",
    description: "Leg and glute focused workout",
    durationMinutes: 35,
    difficulty: "Intermediate",
  ),
  Workout(
    id: 6,
    title: "Core Crusher",
    description: "Strengthen abs and core muscles",
    durationMinutes: 25,
    difficulty: "Beginner",
  ),
  Workout(
    id: 7,
    title: "Power Yoga",
    description: "Dynamic yoga for strength and balance",
    durationMinutes: 45,
    difficulty: "Advanced",
  ),
  Workout(
    id: 8,
    title: "Cardio Burn",
    description: "Fat burning cardio session",
    durationMinutes: 30,
    difficulty: "Intermediate",
  ),
  Workout(
    id: 9,
    title: "Stretch & Relax",
    description: "Full body stretching and relaxation",
    durationMinutes: 20,
    difficulty: "Beginner",
  ),
  Workout(
    id: 10,
    title: "Abs & Core",
    description: "Targeted abs and core workout",
    durationMinutes: 20,
    difficulty: "Intermediate",
  ),
  Workout(
    id: 11,
    title: "Bootcamp Training",
    description: "Military-style full body training",
    durationMinutes: 50,
    difficulty: "Advanced",
  ),
  Workout(
    id: 12,
    title: "Pilates Flow",
    description: "Low impact pilates workout",
    durationMinutes: 35,
    difficulty: "Beginner",
  ),
  Workout(
    id: 13,
    title: "Endurance Run",
    description: "Improve cardiovascular endurance",
    durationMinutes: 40,
    difficulty: "Advanced",
  ),
  Workout(
    id: 14,
    title: "Mobility Training",
    description: "Increase joint mobility and flexibility",
    durationMinutes: 25,
    difficulty: "Beginner",
  ),
  Workout(
    id: 15,
    title: "Strength & Conditioning",
    description: "Total body strength and conditioning",
    durationMinutes: 45,
    difficulty: "Intermediate",
  ),
  Workout(
    id: 16,
    title: "Quick Sweat",
    description: "Short and intense workout",
    durationMinutes: 15,
    difficulty: "Beginner",
  ),
  Workout(
    id: 17,
    title: "Functional Fitness",
    description: "Improve everyday movement patterns",
    durationMinutes: 35,
    difficulty: "Intermediate",
  ),
  Workout(
    id: 18,
    title: "Boxing Cardio",
    description: "Cardio workout inspired by boxing",
    durationMinutes: 30,
    difficulty: "Advanced",
  ),
  Workout(
    id: 19,
    title: "Evening Stretch",
    description: "Relaxing stretch routine before bed",
    durationMinutes: 20,
    difficulty: "Beginner",
  ),
  Workout(
    id: 20,
    title: "Full Body Burn",
    description: "High calorie burn full body workout",
    durationMinutes: 45,
    difficulty: "Advanced",
  ),
];
